# Generated by Django 5.2.15 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("normal", "Normal"), ("demo", "Demo")],
                default="normal",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
