# Generated by Django 5.2.15 on 2026-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0001_initial"),
        ("recommendation", "0007_replace_with_operation_ledger"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolved_at__isnull", True), ("status", "pending")),
                    models.Q(
                        models.Q(("status", "pending"), _negated=True),
                        ("resolved_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="rec_op_resolution_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", models.F("supersedes_id")), _negated=True),
                name="rec_op_not_self_superseding",
            ),
        ),
    ]
