# Generated by Django 5.2.15 on 2026-06-06 23:42

from decimal import Decimal
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, default="", max_length=200)),
                ("training_plan_id", models.UUIDField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "workout_type",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("conditioning", "Conditioning"),
                            ("cardio", "Cardio"),
                            ("mobility", "Mobility"),
                            ("recovery", "Recovery"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            (
                                "recommended_change_pending",
                                "Recommended change pending",
                            ),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("modified", "Modified"),
                        ],
                        default="planned",
                        max_length=64,
                    ),
                ),
                (
                    "planned_intensity",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("planned_duration_minutes", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_strain",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-scheduled_date", "name"],
            },
        ),
    ]
