# Generated by Django 5.2.15 on 2026-06-07 22:50

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0003_trainingplan_workoutexercise_seed_exercises"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="default_intensity",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscle_groups",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="distance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="intensity",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
