spring.datasource.url=jdbc:postgresql://localhost:5432/whoop_ai_coach
spring.datasource.username=whoop_ai_coach
spring.datasource.password=whoop_ai_coach
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
