# Generated by Django 5.2.15 on 2026-08-18 00:14

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coaching", "0004_coach_message_view_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachGlobalMonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(unique=True)),
                (
                    "spent_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal(0), max_digits=12
                    ),
                ),
                (
                    "reserved_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal(0), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("spent_usd__gte", 0)),
                        name="coach_global_monthly_spent_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved_usd__gte", 0)),
                        name="coach_global_monthly_reserved_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CoachUserMonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                (
                    "spent_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal(0), max_digits=12
                    ),
                ),
                (
                    "reserved_usd",
                    models.DecimalField(
                        decimal_places=6, default=Decimal(0), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_monthly_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoachBudgetReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.UUIDField(unique=True)),
                ("reserved_usd", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "actual_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("released", "Released"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_budget_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "global_monthly_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="coaching.coachglobalmonthlyusage",
                    ),
                ),
                (
                    "user_monthly_usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="coaching.coachusermonthlyusage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="coachusermonthlyusage",
            constraint=models.UniqueConstraint(
                fields=("user", "period_start"), name="coach_user_monthly_usage_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="coachusermonthlyusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("spent_usd__gte", 0)),
                name="coach_user_monthly_spent_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="coachusermonthlyusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_usd__gte", 0)),
                name="coach_user_monthly_reserved_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="coachbudgetreservation",
            index=models.Index(
                fields=["status", "created_at"], name="coach_budget_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coachbudgetreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_usd__gte", 0)),
                name="coach_budget_reservation_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="coachbudgetreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_usd__isnull", True),
                    ("actual_usd__gte", 0),
                    _connector="OR",
                ),
                name="coach_budget_actual_nonnegative",
            ),
        ),
    ]
